name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 🚀 Quick Start

  To quickly launch the **Live CMAF Transcoder** on your machine, download and execute the `run.sh` script:

  ```sh
  curl -L https://github.com/sessystems/live-cmaf-transcoder/releases/latest/download/run.sh | bash
  ```

  For more information, check out the [README](https://github.com/sessystems/live-cmaf-transcoder)

  ## Changes

  $CHANGES