services:
  live-cmaf-transcoder-redis:
    image: redis:8-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning --notify-keyspace-events KEA
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - data:/data

volumes:
  data: