services:
  live-cmaf-transcoder-no-gpu:
    image: ghcr.io/sessystems/live-cmaf-transcoder:latest
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id
    ports:
      - "8888:8888"
    devices:
      - "/dev/dri:/dev/dri"

  live-cmaf-transcoder-nvidia:
    image: ghcr.io/sessystems/live-cmaf-transcoder:latest
    volumes:
      - /etc/machine-id:/etc/machine-id
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id
    ports:
      - "8888:8888"
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]
    profiles: ["nvidia"]

volumes:
  data:
  ramdisk:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
