x-live-cmaf-transcoder: &live-cmaf-transcoder
  image: ghcr.io/sessystems/live-cmaf-transcoder:latest
  volumes:
    - /etc/machine-id:/etc/machine-id
    - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id
    - data:/var/lib/redis
  ports:
    - "80:8888"
    - "6379:6379"
  environment:
    - "BASE_URL=${BASE_URL:-http:/localhost}"
    - "REDIS_URL=${REDIS_URL:-redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@localhost:6379}"
    - "RUST_LOG=warn"
      
services:

  live-cmaf-transcoder-no-gpu:
    <<: *live-cmaf-transcoder
    profiles:
      - ''

  live-cmaf-transcoder-intel-gpu:
    <<: *live-cmaf-transcoder
    devices:
      - "/dev/dri:/dev/dri"
    profiles:
      - 'intel'

  live-cmaf-transcoder-gpu:
    <<: *live-cmaf-transcoder
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]
    profiles:
      - 'gpu'

volumes:
  data:
  ramdisk:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
