##
# Docker Compose Configuration for Live CMAF Transcoder
#
# USAGE:
#
# 1. **Run without GPU acceleration (software-only mode)**:
#    This runs the transcoder using CPU-only encoding.
#    Suitable for environments without GPU support.
#    $ docker compose up
#
# 2. **Run with Intel GPU support**:
#    Enables hardware acceleration using Intel iGPU via VAAPI.
#    Requires access to /dev/dri on the host.
#    $ docker compose --profile intel up 
#
# 3. **Run with Intel + NVIDIA GPU support**:
#    Enables hardware acceleration using both Intel and NVIDIA GPUs.
#    NVIDIA container toolkit must be installed on the host.
#    $ docker compose --profile gpu up 
#
##

x-live-cmaf-transcoder: &live-cmaf-transcoder
  image: ghcr.io/sessystems/live-cmaf-transcoder:latest
  volumes:
    - /etc/machine-id:/etc/machine-id
    - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id
    - data:/data
  ports:
    - "${SERVER_PORT-80}:8888"
    - "${REDIS_PORT-6379}:6379"
  environment:
    - "BASE_URL=${BASE_URL:-http://localhost}"
    - "SERVER_NAME=${SERVER_NAME:-}"
    - "SERVER_UID=${SERVER_UID:-}"
    - "REDIS_URL=${REDIS_URL:-}"
    - "REDIS_SERVICE_DISABLED=${REDIS_SERVICE_DISABLED:-false}"
    - "REDIS_PASSWORD=${REDIS_PASSWORD:-eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81}"
    - "RUST_LOG=warn"
      
services:

  live-cmaf-transcoder-no-gpu:
    <<: *live-cmaf-transcoder
    profiles:
      - ''

  live-cmaf-transcoder-intel-gpu:
    <<: *live-cmaf-transcoder
    devices:
      - "/dev/dri:/dev/dri"
    profiles:
      - 'intel'

  live-cmaf-transcoder-gpu:
    <<: *live-cmaf-transcoder
    devices:
      - "/dev/dri:/dev/dri"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]
    profiles:
      - 'gpu'

volumes:
  data:
  ramdisk:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
