name: Dockerhub

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  buildx:
    name: Build and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Extract version from tag
        run: |
          REF="${{ github.ref }}"
          if [[ "$REF" == refs/heads/* ]]; then
            VERSION=${REF#refs/heads/}
          elif [[ "$REF" == refs/tags/v* ]]; then
            VERSION=${REF#refs/tags/v}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      -
        name: Checkout
        uses: actions/checkout@v4  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Push
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          targets: all
          push: true
