name: Packages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (e.g. refs/tags/v1.0.0)"
        required: true

permissions:
  packages: write
  contents: write

jobs:
  buildx:
    name: Build and push Packages
    runs-on: ubuntu-latest
    steps:
      - 
        name: Extract version from tag
        run: |
          REF="${{ github.ref }}"
          if [[ "$REF" == refs/heads/* ]]; then
            VERSION=${REF#refs/heads/}
          elif [[ "$REF" == refs/tags/v* ]]; then
            VERSION=${REF#refs/tags/v}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set REGISTRY
        run: echo "REGISTRY=ghcr.io" >> $GITHUB_ENV
        
      -
        name: Checkout
        uses: actions/checkout@v4  

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  

      -
        name: Build and Push
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          targets: all
          push: true


      - name: Dispatch Packages Event
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: package-created
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
